### ISSUE TITLE
jitpack.io artifact unavailable

### ISSUE THREAD

**Issue by mjc-** [daveallie/prisma-graphics#1]
Not sure if this is something that needs fixing here, or on jitpack's end, but the fetching of the artifacts for this project are currently broken.

Example curl output included:
$ curl -sSv https://jitpack.io/com/github/daveallie/prisma-graphics/1.0.1/prisma-graphics-1.0.1.pom
-   Trying 104.24.22.62...
- Connected to jitpack.io (104.24.22.62) port 443 (#0)
- TLS 1.2 connection using TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
- Server certificate: ssl387629.cloudflaressl.com
- Server certificate: COMODO ECC Domain Validation Secure Server CA 2
- Server certificate: COMODO ECC Certification Authority
- Server certificate: AddTrust External CA Root
  > GET /com/github/daveallie/prisma-graphics/1.0.1/prisma-graphics-1.0.1.pom HTTP/1.1
  > Host: jitpack.io
  > User-Agent: curl/7.43.0
  > Accept: _/_
  >
  < HTTP/1.1 404 Not found
  < Server: cloudflare-nginx
  < Date: Tue, 05 Apr 2016 19:34:29 GMT
  < Content-Length: 9
  < Connection: keep-alive
  < Set-Cookie: __cfduid=d7ae71b09106024e5352d049dd99c67d31459884869; expires=Wed, 05-Apr-17 19:34:29 GMT; path=/; domain=.jitpack.io; HttpOnly
  < Cache-Control: max-age=60,
  < Last-Modified: Tue, 05 Apr 2016 20:34:29 BST
  < Expires: Tue, 05 Apr 2016 20:35:29 BST
  < CF-Cache-Status: EXPIRED
  < CF-RAY: 28ef7010478c1ecb-SJC
  <
- Connection #0 to host jitpack.io left intact
  Not found

**Comment by daveallie** [comment]
Could have just been jitpack rebuilding the package, everything looks fine for me when making the same request.

``` bash
curl -sSv https://jitpack.io/com/github/daveallie/prisma-graphics/1.0.1/prisma-graphics-1.0.1.pom
*   Trying 104.24.23.62...
* Connected to jitpack.io (104.24.23.62) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
* Server certificate: ssl387629.cloudflaressl.com
* Server certificate: COMODO ECC Domain Validation Secure Server CA 2
* Server certificate: COMODO ECC Certification Authority
* Server certificate: AddTrust External CA Root
> GET /com/github/daveallie/prisma-graphics/1.0.1/prisma-graphics-1.0.1.pom HTTP/1.1
> Host: jitpack.io
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: cloudflare-nginx
< Date: Wed, 06 Apr 2016 02:00:11 GMT
< Content-Type: text/xml
< Content-Length: 1550
< Connection: keep-alive
< Set-Cookie: __cfduid=d403781f9aaf3689971b9beddc4575bed1459908011; expires=Thu, 06-Apr-17 02:00:11 GMT; path=/; domain=.jitpack.io; HttpOnly
< ETag: e9871c6b9399b3e26019a69a58bd207002634475
< Cache-Control: public, max-age=86400
< Last-Modified: Wed, 06 Apr 2016 02:58:10 BST
< CF-Cache-Status: HIT
< Expires: Thu, 07 Apr 2016 02:00:11 GMT
< CF-RAY: 28f1a50dbe780b26-SYD
<
<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.github.daveallie</groupId>
  <artifactId>prisma-graphics</artifactId>
  <version>1.0.1</version>
  <name>daveallie/prisma-graphics</name>
  <url>https://github.com/daveallie/prisma-graphics</url>
  <inceptionYear>2015</inceptionYear>
  <licenses>
    <license>
      <name>MIT License</name>
      <url>https://api.github.com/licenses/mit</url>
      <distribution>repo</distribution>
    </license>
  </licenses>
  <developers>
    <developer>
      <id>daveallie</id>
      <name>Dave Allie</name>
      <email></email>
    </developer>
  </developers>
  <scm>
    <connection>scm:git://github.com/daveallie/prisma-graphics.git</connection>
    <developerConnection>scm:git://github.com/daveallie/prisma-graphics.git</developerConnection>
    <url>git://github.com/daveallie/prisma-graphics.git</url>
  </scm>
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  <build>
    <sourceDirectory>${project.basedir}/src</sourceDirectory>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>2.3.2</version>
        <configuration>
          <source>1.5</source>
          <target>1.5</target>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
* Connection #0 to host jitpack.io left intact
```

**Comment by mjc-** [comment]
Kind of silly for them to nuke the whole project while "rebuilding", I can confirm that prisma-graphics works now, but funnily enough, after reverting my pom.xml changes to work around the problem (using locally mvn installed jars), I noticed that tnoodle-scrambles is still giving a 404, not exactly a ringing endorsement for jitpack's stability :/
